### ISSUE TITLE
codeml stalling with default tmp folder name

### ISSUE THREAD

**Issue by ricardovialle** [arzwa/wgd#1]
Hi,

Running the "wgd ks" under default temporary folder name causes codeml to fail to find the .ctrl file. 
Then it never completes the process.
Probably is some character used in the folder name. 
Specifying a simple name with "-tmp" everything runs smoothly.

Cheers,
Ricardo

**Comment by arzwa** [comment]
Hi Ricardo,

I notice I didn't address this issue. The reason is probably a too long filename, this will be fixed in the next version (which is coming soon). If it is indeed due to a weird character, this is readily fixed by using the `-tmp` option so I will close this issue.

Best,
Arthur
