### ISSUE TITLE
Downstream analyses after wgd - dating WGD ?

### ISSUE THREAD

**Issue by BiodivGenomic** [arzwa/wgd#11]
Hi,
it's not really an issue... I would like to date the WGD events using the method in Vanneste et al (2014), using the anchors identified by wgd. As both wgd and the method used by Vanneste et al. came from the same lab, I wish there is some congruence/integration in the output files formats ? 
So, can I use outputs from wgd to feed inparanoid, or is there an easier pipeline (the method used in Vanneste et al. seems entirely custom-made, or at least mostly manual...) that would integrate the output of wgd in the Vanneste et al. method ?

**Comment by arzwa** [comment]
Hi, I'd like to keep this github page to track issues ;), could you drop me an email, so we can converse elsewhere on this? Thanks

**Comment by arzwa** [comment]
BTW: my email is `arzwa <at> psb <dot> vib-ugent <dot> be`
