### ISSUE TITLE
cannot find testdata

### ISSUE THREAD

**Issue by Mar-y** [arzwa/wgd#22]
Hey, 
I just started using wgd and wanted to run it with the testdata, but I couldn't find the data
I used: 
wget ftp://ftp.psb.ugent.be/pub/plaza/plaza_public_dicots_04//Fasta/cds.ath.fasta.gz
and 
wget ftp://ftp.psb.ugent.be/pub/plaza/plaza_public_dicots_04//GFF/ath/Arabidopsis_thaliana.COL0.Araport11.longest_transcript.all_features.gff3.gz

but for both I got the issue "No such file" 
Are the files renamed or moved to another place maybe?
Thanks for any help
regards

**Comment by arzwa** [comment]
Hi, the urls seem to have changed indeed. Please find up to date example data sets at the PLAZA  website: https://bioinformatics.psb.ugent.be/plaza/versions/plaza_v4_dicots/download/index. (e.g. CDS data for *Arabidopsis* ftp://ftp.psb.ugent.be/pub/plaza/plaza_public_dicots_04/Fasta/cds.selected_transcript.ath.fasta.gz)
