### ISSUE TITLE
install wgd without internet connection

### ISSUE THREAD

**Issue by xiaoyezao** [arzwa/wgd#25]
Hi,

I am using a cluster that has no internet connection. How to install wgd without an internet connection?

bests,
TF

**Comment by arzwa** [comment]
Hi, this is not really a question about `wgd`. It depends on the python installation and the computer environment in general of the relevant cluster. Also I have no idea which of the required non-python dependencies you have installed. I am closing this issue, as I won't be able to help, you might want to ask the cluster administrator for more help, the `setup.py` file and the docs indicate the dependencies.

Best, Arthur
