### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by U201412486** [arzwa/wgd#28]
Hi,
  When I try to install the software "wgd",It report the error like this below.
```
  ERROR: Could not install packages due to an EnvironmentError: [(/software/wgd/.git/objects/pack/pack-0f9dbb53be2abbe014d924ad3322cd845548336c.idx', '/tmp/pip-req-build-hxhrkvnl/.git/objects/pack/pack-0f9dbb53be2abbe014d924ad3322cd845548336c.idx', "[Errno 13] Permission denied: '/tmp/pip-req-build-hxhrkvnl/.git/objects/pack/pack-0f9dbb53be2abbe014d924ad3322cd845548336c.idx'"), ('/software/wgd/.git/objects/pack/pack-0f9dbb53be2abbe014d924ad3322cd845548336c.pack', '/tmp/pip-req-build-hxhrkvnl/.git/objects/pack/pack-0f9dbb53be2abbe014d924ad3322cd845548336c.pack', "[Errno 13] Permission denied: '/tmp/pip-req-build-hxhrkvnl/.git/objects/pack/pack-0f9dbb53be2abbe014d924ad3322cd845548336c.pack'")]
```
  And I do not have root authority.Can you give me some advice?
  Thanks,

**Comment by arzwa** [comment]
Hi, try the `--user` flag when doing `pip install`. So from within the clone repository do

```
pip install --user ./
```

that will install `wgd` somwhere where you do have the right permissions (usually your home folder, in my case its `~/.local/`). Alternatively you can use a virtual environment using `venv`.

**Comment by U201412486** [comment]
Hi,
  It reports the same error  with the code of "pip install --user ./".
  And how can I use a virtual environment using venv ? 
  Thanks,

**Comment by arzwa** [comment]
Please refer to [this issue](https://github.com/arzwa/wgd/issues/4#) for using `virtualenv`.

**Comment by U201412486** [comment]
It also does not work .And I use python3.7.3.

**Comment by arzwa** [comment]
Well, I will need some more information to be able to help you. The following works for me

```
virtualenv -p python3.7  ./venv  
# if the above does not work, try `python3 -m virtualenv -p python3.7  ./venv `
cd venv
source ./bin/activate
git clone https://github.com/arzwa/wgd.git
cd wgd
pip install .
# if you get an error about numpy try to run `pip install numpy` before `pip install .`
```

Then I am able to run `wgd`. If the `wgd` command is not found, try `python3 path_to_wgd_directory/wgd_cli.py` instead.

**Comment by U201412486** [comment]
It is very strange.The following does not work for me
`virtualenv -p python3.7  ./venv  
cd venv
source ./bin/activate
git clone https://github.com/arzwa/wgd.git
cd wgd
pip install .`
It reports the following error 
`ERROR: Could not install packages due to an EnvironmentError: [('/software/wgd/venv/wgd/.git/objects/pack/pack-0f9dbb53be2abbe014d924ad3322cd845548336c.idx', '/tmp/pip-req-build-nqgyyutc/.git/objects/pack/pack-0f9dbb53be2abbe014d924ad3322cd845548336c.idx', "[Errno 13] Permission denied: '/tmp/pip-req-build-nqgyyutc/.git/objects/pack/pack-0f9dbb53be2abbe014d924ad3322cd845548336c.idx'"), ('/software/wgd/venv/wgd/.git/objects/pack/pack0f9dbb53be2abbe014d924ad3322cd845548336c.pack', '/tmp/pip-req-build-nqgyyutc/.git/objects/pack/pack-0f9dbb53be2abbe014d924ad3322cd845548336c.pack', "[Errno 13] Permission denied: '/tmp/pip-req-build-nqgyyutc/.git/objects/pack/pack0f9dbb53be2abbe014d924ad3322cd845548336c.pack'")]`
