### ISSUE TITLE
Error: Invalid value for '--ks_range' / '-r'

### ISSUE THREAD

**Issue by mars327** [arzwa/wgd#34]
Hi,

When I execute the command ( wgd viz -r 0.005,2 -ks ./ks_dir/), I encounter this error：
Error: Invalid value for '--ks_range' / '-r': 0.005,2 is not a valid floating point value

Is this parameter (-r) in the wrong format? How should this parameter be set?

Looking forward to your reply.

with best regards
Xupeng

**Comment by arzwa** [comment]
Hi, you can just use `-ks_range 0.005 2`.
