### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by qiuxx221** [arzwa/wgd#37]
Hi, 

This might be silly, I used this program a while ago, everything works great. Now I am trying to install it on the new env using pip install wgd, but the installation doesn't work anymore with error msg below
```
ERROR: Could not find a version that satisfies the requirement wgd (from versions: none)
ERROR: No matching distribution found for wgd
```
Just to have positive control, I did pip install bar to make sure the pip is working properly. My current python version was 3.6. Would you please take a look and see what might be the reason? 

Thank you!

**Comment by arzwa** [comment]
I guess this is resolved? I'll answer anyway: `wgd` is currently not in the package index, so you must download/clone the repository and run `pip install <path/to/wgd/directory>` locally.

**Comment by qiuxx221** [comment]
Thank you, and yes, I figured it out.
