### ISSUE TITLE
Package not on pypi

### ISSUE THREAD

**Issue by bedroesb** [arzwa/wgd#40]
Is it possible that wgd is at this moment not installable through pip without cloning the github repo?
https://pypi.org/search/?q=wgd

**Comment by arzwa** [comment]
Yes, that is true, the package is at the moment not registered. I was planning to register it once I manage to get v2.0 working decently.

**Comment by bedroesb** [comment]
Maybe it might be useful to change the documentation than :)  I btw uploaded I-adhore to Github after approval with the involved persons: https://github.com/VIB-PSB/i-ADHoRe. Might be handy to add it to the singularity container.

**Comment by arzwa** [comment]
Hmm, when did that `pip install wgd` slip into the README... Thanks for pointing that out. Also, great to see an I-ADHoRe repo, thanks!
