### ISSUE TITLE
Singularity I-ADHoRe not working

### ISSUE THREAD

**Issue by pedrobdfp** [arzwa/wgd#42]
Hi

I am using WGD on an insect genome, and I have been using the singularity container within a Centos 7 Virtual Machine.
I was following the [basic tutorials](https://wgd.readthedocs.io/en/latest/wgd_cli.html#wgd-cli), but I came across an error on the third command line (singularity exec wgd.simg wgd syn):

ERROR     i-adhora executable not found!
ERROR     Could not run all software, exit here.

I believe this is an error with the container instalation?

best;
Pedro

**Comment by arzwa** [comment]
Hi Pedro, I-ADHoRe is currently not available in the container installation. The software used to be unavailable for non-interactive download on the net, however currently it is (https://github.com/VIB-PSB/i-ADHoRe/issues), so I might update the container in the future to also support synteny inference with I-ADHoRe.

**Comment by Cecilia-Sensalari** [comment]
Hi,
Singularity has been updated, now it can run i-ADHoRe (see README).

Cheers,
Cecilia
