### ISSUE TITLE
PAML installation in Singularity container

### ISSUE THREAD

**Issue by Cecilia-Sensalari** [arzwa/wgd#57]
Hi,

I've seen that you added a section in the readme to install PAML from source, but in the Singularity file PAML is still installed with apt-get. I suggest to add something like this to the Singularity file:
`apt-get install -y wget && wget http://abacus.gene.ucl.ac.uk/software/paml4.9j.tgz && tar -xzf paml4.9j.tgz && cd paml4.9j/src && make -f Makefile && mv codeml /bin && cd ../..`
It's slightly different from what you wrote in your readme: I had to move codeml to /bin to make it work and replace pushd/popd with cd.

Bests,
Cecilia

**Comment by arzwa** [comment]
Hi Cecilia, thanks for the info. Feel free to do a PR with the proposed changes (I haven't used Singularity in ages and haven't been maintaining it, so if you could update with a working Singularity file that would be great), else I'll have a look at it later.

**Comment by Cecilia-Sensalari** [comment]
Alright! I'm still testing the PAML installation with this new line within the ksrates container, when I have something final with it I can make the pull request with similar changes for your wgd container :)
