### ISSUE TITLE
noninteractive apt-get

### ISSUE THREAD

**Issue by mercanca** [arzwa/wgd#6]
There is an issue at wgd.shub. tzdata packet ask timezone interactively, but we can't answer this question. Because of that reason, the apt-get line should be modified like below to work:  

```
apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -yq install python3-pip python3-tk git wget \
	    build-essential mcl ncbi-blast+ muscle mafft prank fasttree phyml paml
```

**Comment by arzwa** [comment]
Thanks a lot! I have updated the `wgd.shub` file as you suggested.
