### ISSUE TITLE
ksd error about Generating plots and No `Omega` value  of some gene pairs

### ISSUE THREAD

**Issue by xzq-script** [arzwa/wgd#64]
Hello,

I really enjoy using this tool for my WGD analysis. For some reason, I have to get the standard error when I run wgd ksd.
1:
 it generated result file about ks.tsv,but no ks.svg.  i guess the reason that may be python lacks certain modules， I will appreciate it if you give me some tips.
![图片](https://user-images.githubusercontent.com/64960057/123364169-8ce46d80-d5a6-11eb-8192-e2bd49c4809e.png)
2:
what the meaning of "No `Omega` value for some gene pairs"
Do you have any advice?

Thank you very much for your help!

**Comment by xzq-script** [comment]
it always pops up such an interface about shell：
![图片](https://user-images.githubusercontent.com/64960057/123365099-30824d80-d5a8-11eb-9152-790854e8d577.png)

**Comment by xzq-script** [comment]
Oh,  I have solved all the problems by myself,  Thank you very much for your help and development.

**Comment by arzwa** [comment]
OK, great to hear :) Maybe if you know how you solved it you can post it here? It might help others facing similar issues.

**Comment by xzq-script** [comment]
Xshell +xmanger
Link to the visual interface of linux
