### ISSUE TITLE
wgd ksd output can not generate the tsv file

### ISSUE THREAD

**Issue by ljl000** [arzwa/wgd#67]
Hi, I performed wgd ksd to calculate Ks value by using transcritome data ,but I can't generate the tsv file. I only get a tmp file folder with sevaral  GF_xxx.Ks, GF_xxx.fasta and  GF_xxx.msa in it. how can i fix this? the result  folder just like this...
![屏幕快照 2021-09-08 22 25 47](https://user-images.githubusercontent.com/43433383/132527922-f98aa17e-093c-480b-bff0-631fa78bb801.png)

**Comment by arzwa** [comment]
Did you get an error message related to generating the `tsv` output? As a workaround you can just concatenate the `GF_*.Ks` files, you will only need to remove the first line of each file and have that only once on top of the concatenated file. Something like this in python should also work (not tested!) 
```python
import os
import pandas as pd
pd.concat([pd.read_csv(f, sep="\t", index_col=0) for f in os.listdir(".")]).to_csv("ksd.tsv", sep="\t")
```

**Comment by arzwa** [comment]
Closing because no response.
