### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by claudiacln87** [arzwa/wgd#7]
Hi I am trying to run All-versus-all Blastp analysis and MCL clustering  but I got this error.
Any suggestions?

```
File "/rhome/ccoleine/.conda/envs/MIC-test/lib/python2.7/site-packages/wgd_cli.py", line 293, in mcl
    inflation_factor, eval_cutoff, output_dir, n_threads)
  File "/rhome/ccoleine/.conda/envs/MIC-test/lib/python2.7/site-packages/wgd_cli.py", line 334, in blast_mcl
    if can_i_run_software(software) == 1:
  File "/rhome/ccoleine/.conda/envs/MIC-test/lib/python2.7/site-packages/wgd/utils.py", line 67, in can_i_run_software
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by arzwa** [comment]
Hi,

It seems you are using `python2.7`. You will need to use either `python3.5` or `python3.6` to be able to use wgd. I would suggest to create a new conda environment or virtualenv with one of the python3 versions as main python version and try again.

Best, Arthur

**Comment by arzwa** [comment]
Hi, 

I haven't had problems with `click` in Python 3 before, it seems to be an issue with Unicode stuff in your environment. Based on what I read here (https://click.palletsprojects.com/en/7.x/python3/#python-3-surrogate-handling), you might be able to make it work by setting a couple of environment variables:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

which are the settings on my machine. 

Hope this helps, Arthur

**Comment by claudiacln87** [comment]
Great, now it works with settings on US machine a en_US.utf-8.
Thank you very much.
I will let you know how my analysis proceed.
Best regards, 
Claudia
