### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by ardy20** [arzwa/wgd#70]
Hi
In stalled wgd in HPC system using conda. But I was not able to run the visualization step. the command below did not pop up the bowser to view the results:

bokeh serve &
Then run
wgd viz -i ./ks_dir

Is there any alternative or web-based tool to view when the tool has not been installed in a local computer (but instaled on a High performance Computers or clusters)?

Regards

**Comment by arzwa** [comment]
There is no web-based tool at the present to do so. You can try to fix the issue with your system admin, install `wgd` locally and run the `viz` command locally, visualize the Ks distributions non-interactively or use some other environment to conduct the visualization yourself (e.g. #24 for some hints on using R). Note that the interactive visualization is not actively maintained.
