### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by FFerraro99** [arzwa/wgd#77]
I have been trying to use the wgd package for analysis of cds files from mollusc genomes. I have been getting a KeyError, and am not sure how to solve this issue.
I the file was from NCBI at https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/905/397/895/GCA_905397895.1_MEDL1/GCA_905397895.1_MEDL1_cds_from_genomic.fna.gz
I removed the colons, and obtained an the mcl file, but when moving to the ksd command, but no ks.tsv file.

```
/usr/local/lib/python3.8/dist-packages/wgd/phy.py in <dictcomp>(.0=<list_iterator object>)
    137         if node.is_leaf():
    138             node.name = id_map[node.name]
    139             id_map[node.name] = node.name  # add identity map for renamed nodes
    140             # to id_map for line below
    141             pairwise_distances[node.name] = {
--> 142                 id_map[x.name]: node.get_distance(x) for x in t.get_leaves()
        x.name = '155173'
        x = Tree node '155173' (0x7f4c44fcfc4)
    143             }
    144         else:
    145             node.name = n
    146             n += 1
                                                                                                                                                   
KeyError: '155173'
```
I have been getting a warning suggesting I raise the max_pairwise parameter, and that 13 largest geen familis were filtered out.
Any possible solutions for this problem?

**Comment by FFerraro99** [comment]
Thank you for your rapid response. For clarification, which data are you suggesting I relable? The cds fasta file?

**Comment by arzwa** [comment]
You can for sure use BioPython, this should work
```python
import Bio.SeqIO
seqs = []
for rec in Bio.SeqIO.parse("./GCF_902806645.1_cgigas_uk_roslin_v1_cds_from_genomic.fna", "fasta"):
    gene_id = rec.id
    new_id = gene_id.split("|")[1]
    rec.id = new_id
    rec.description = ""
    seqs.append(rec)  
Bio.SeqIO.write(seqs, "seqs.renamed.fasta", "fasta")
```

**Comment by FFerraro99** [comment]
Thank you so much, this is of infinite help
