### ISSUE TITLE
WARNING:root:No codeml results

### ISSUE THREAD

**Issue by abcbot123** [arzwa/wgd#88]
Hi, I uesd WGD with the command :
python3 wgd-1.1.2/wgd_cli.py ksd -o ./ -n 8 ./newCDS.fa.blast.tsv.mcl newCDS.fa

2024-01-04 00:37:01: INFO	codeml stdout: AAML in paml version 4.9j, October 2019
2024-01-04 00:37:01: INFO	codeml stderr: Error: file name empty..
2024-01-04 00:37:01: INFO	codeml found
2024-01-04 00:37:01: INFO	mafft stdout: 
2024-01-04 00:37:01: INFO	mafft stderr: v7.453 (2019/Nov/8)
2024-01-04 00:37:01: INFO	FastTree stdout: 
2024-01-04 00:37:01: INFO	FastTree stderr: Unknown or incorrect use of option --version

What are these stderr? Are those effect to the output?

I got these errors as well. How can I fix it?

2024-01-04 00:37:18: WARNING	There were 0 warnings during translation
2024-01-04 00:37:18: INFO	Started whole paranome Ks analysis
2024-01-04 00:37:18: WARNING	Filtered out the 1 largest gene families because n*(n-1)/2 > `max_pairwise`
2024-01-04 00:37:18: WARNING	If you want to analyse these large families anyhow, please raise the `max_pairwise` parameter. 
2024-01-04 00:37:18: INFO	Started analysis in parallel (n_threads = 8)
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000008.codeml
WARNING:root:No codeml results for GF_000008!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000007.codeml
WARNING:root:No codeml results for GF_000007!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000010.codeml
WARNING:root:No codeml results for GF_000010!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000004.codeml
WARNING:root:No codeml results for GF_000004!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000013.codeml
WARNING:root:No codeml results for GF_000013!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000014.codeml
WARNING:root:No codeml results for GF_000014!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000012.codeml
WARNING:root:No codeml results for GF_000012!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000016.codeml
WARNING:root:No codeml results for GF_000016!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000018.codeml
WARNING:root:No codeml results for GF_000018!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000019.codeml
WARNING:root:No codeml results for GF_000019!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000020.codeml
WARNING:root:No codeml results for GF_000020!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000022.codeml
WARNING:root:No codeml results for GF_000022!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000023.codeml
WARNING:root:No codeml results for GF_000023!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000024.codeml
WARNING:root:No codeml results for GF_000024!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000025.codeml
WARNING:root:No codeml results for GF_000025!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000026.codeml
WARNING:root:No codeml results for GF_000026!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000028.codeml
WARNING:root:No codeml results for GF_000028!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000029.codeml
WARNING:root:No codeml results for GF_000029!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000031.codeml
WARNING:root:No codeml results for GF_000031!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000032.codeml
WARNING:root:No codeml results for GF_000032!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000034.codeml
WARNING:root:No codeml results for GF_000034!
ERROR:root:Not all gene pairs present in /var/lib/condor/execute/slot1/dir_2232/ks_tmp.3c8cc74cc935be/GF_000036.codeml
WARNING:root:No codeml results for GF_000036!

**Comment by arzwa** [comment]
Please consider using the latest version of `wgd` available [here](https://github.com/heche-psb/wgd). If you would still have issues, you can raise them there.
