### ISSUE TITLE
wgd syn #Run error

### ISSUE THREAD

**Issue by YuJiang0121** [arzwa/wgd#93]
I ran "wgd dmd" and "wgd ksd" before and everything worked fine, but running "wgd syn" failed, 
wgd syn -o PeniCBMAcds.syn -ks PeniCBMAcds.ksd/PeniCBMAcds.fasta.ks.tsv -f mRNA -a ID PeniCBMAcds.gff PeniCBMAcds.dmd/PeniCBMAcds.fasta.mcl
this is the error content：
(wgd) yu123@yu123-PC:~/Desktop/T7wgd/ceshi$ wgd syn -o PeniCBMAcds.syn -ks PeniCBMAcds.ksd/PeniCBMAcds.fasta.ks.tsv -f mRNA -a ID PeniCBMAcds.gff PeniCBMAcds.dmd/PeniCBMAcds.fasta.mcl

2024-10-17 20:47:57: INFO       i-adhore stdout: This is i-ADHoRe v3.0.
Copyright (c) 2002-2010, Flanders Interuniversity Institute for Biotechnology, VIB.
Algorithm designed by Klaas Vandepoele, Cedric Simillion, Jan Fostier, Dieter De Witte,
Koen Janssens, Sebastian Proost, Yvan Saeys and Yves Van de Peer.

Process 1/1 is alive on yu123-PC.
2024-10-17 20:47:57: INFO       i-adhore stderr: Error opening the settings file: -version
2024-10-17 20:47:57: INFO       Made output directory PeniCBMAcds.syn
2024-10-17 20:47:57: INFO       Parsing GFF file
2024-10-17 20:47:58: INFO       Writing gene lists
2024-10-17 20:47:58: INFO       Writing families file
2024-10-17 20:47:58: INFO       Writing configuration file
2024-10-17 20:47:58: INFO       Running I-ADHoRe 3.0
2024-10-17 20:48:01: WARNING    WARNING: Maximum allowed number of gaps in the alignment not specified.  Setting to cluster_gap.                                          
WARNING: Tandem gap size not correct in settings file. Using default (gap_size / 2)  
                                                                                     
2024-10-17 20:48:01: INFO
This is i-ADHoRe v3.0.
Copyright (c) 2002-2010, Flanders Interuniversity Institute for Biotechnology, VIB.
Algorithm designed by Klaas Vandepoele, Cedric Simillion, Jan Fostier, Dieter De Witte,
Koen Janssens, Sebastian Proost, Yvan Saeys and Yves Van de Peer.

Process 1/1 is alive on yu123-PC.

************* i-ADHoRe parameters *************
        Number of genelists = 749
        Blast table = PeniCBMAcds.syn/families.tsv
        Output path = PeniCBMAcds.syn/i-adhore-out/
        Gap size = 30
        Cluster gap size = 35
        Cloud gap size = 0
        Cloud cluster gap size = 0
        Max gaps in alignment = 35
        Tandem gap = 15
        Flush output = 1000
        Q-value = 0.75
        Anchorpoints = 3
        Probability cutoff = 0.01
        Cloud filtering method = Binomial
        Level 2 only = false
        Use family = true
        Write statistics = false
        Alignment method = GreedyGraphbased4
        Multiple hypothesis correction = FDR
        Number of threads = 1
        Compare aligners = false
        Collinear searches only
        Visualize GHM.png = false
        Visualize Alignment = true
        Verbose output = true
************ END i-AdDHoRe parameters *********

Creating dataset...                     done. (time: 0.00943708s)
Mapping gene families...                done. (time: 0.010159s)
Remapping tandem duplicates...  done. (time: 0.006392s)
Writing genelists file...               done. (time: 0.042654s)
Collinear Search
Level 2 multiplicon detection...        done. (time: 2.20706s)
Profile detection...
140 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
139 multiplicons to evaluate - evaluating level 2 multiplicon... 3 new multiplicons found.
141 multiplicons to evaluate - evaluating level 3 multiplicon... 0 new multiplicons found.
140 multiplicons to evaluate - evaluating level 3 multiplicon... 0 new multiplicons found.
139 multiplicons to evaluate - evaluating level 3 multiplicon... 0 new multiplicons found.
138 multiplicons to evaluate - evaluating level 2 multiplicon... 5 new multiplicons found.
142 multiplicons to evaluate - evaluating level 3 multiplicon... 5 new multiplicons found.
146 multiplicons to evaluate - evaluating level 4 multiplicon... 1 new multiplicons found.
146 multiplicons to evaluate - evaluating level 5 multiplicon... too few aligned homologs
145 multiplicons to evaluate - evaluating level 4 multiplicon... 3 new multiplicons found.
147 multiplicons to evaluate - evaluating level 5 multiplicon... 0 new multiplicons found.
146 multiplicons to evaluate - evaluating level 5 multiplicon... 0 new multiplicons found.
145 multiplicons to evaluate - evaluating level 5 multiplicon... 0 new multiplicons found.
144 multiplicons to evaluate - evaluating level 4 multiplicon... all elements masked
143 multiplicons to evaluate - evaluating level 4 multiplicon... all elements masked
142 multiplicons to evaluate - evaluating level 4 multiplicon... all elements masked
141 multiplicons to evaluate - evaluating level 3 multiplicon... all elements masked
140 multiplicons to evaluate - evaluating level 3 multiplicon... all elements masked
139 multiplicons to evaluate - evaluating level 3 multiplicon... all elements masked
138 multiplicons to evaluate - evaluating level 3 multiplicon... all elements masked
137 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
136 multiplicons to evaluate - evaluating level 2 multiplicon... 5 new multiplicons found.
140 multiplicons to evaluate - evaluating level 3 multiplicon... 1 new multiplicons found.
140 multiplicons to evaluate - evaluating level 4 multiplicon... 3 new multiplicons found.
142 multiplicons to evaluate - evaluating level 5 multiplicon... 2 new multiplicons found.
143 multiplicons to evaluate - evaluating level 6 multiplicon... 2 new multiplicons found.
144 multiplicons to evaluate - evaluating level 7 multiplicon... 1 new multiplicons found.
144 multiplicons to evaluate - evaluating level 8 multiplicon... 0 new multiplicons found.
143 multiplicons to evaluate - evaluating level 7 multiplicon... all elements masked
142 multiplicons to evaluate - evaluating level 6 multiplicon... all elements masked
141 multiplicons to evaluate - evaluating level 5 multiplicon... all elements masked
140 multiplicons to evaluate - evaluating level 5 multiplicon... all elements masked
139 multiplicons to evaluate - evaluating level 3 multiplicon... 0 new multiplicons found.
138 multiplicons to evaluate - evaluating level 3 multiplicon... all elements masked
137 multiplicons to evaluate - evaluating level 3 multiplicon... all elements masked
136 multiplicons to evaluate - evaluating level 3 multiplicon... all elements masked
135 multiplicons to evaluate - evaluating level 2 multiplicon... 1 new multiplicons found.
135 multiplicons to evaluate - evaluating level 3 multiplicon... 0 new multiplicons found.
134 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
133 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
132 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
131 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
130 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
129 multiplicons to evaluate - evaluating level 2 multiplicon... 2 new multiplicons found.
130 multiplicons to evaluate - evaluating level 3 multiplicon... 1 new multiplicons found.
130 multiplicons to evaluate - evaluating level 4 multiplicon... 0 new multiplicons found.
129 multiplicons to evaluate - evaluating level 3 multiplicon... all elements masked
128 multiplicons to evaluate - evaluating level 2 multiplicon... 1 new multiplicons found.
128 multiplicons to evaluate - evaluating level 3 multiplicon... 0 new multiplicons found.
127 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
126 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
125 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
124 multiplicons to evaluate - evaluating level 2 multiplicon... 1 new multiplicons found.
124 multiplicons to evaluate - evaluating level 3 multiplicon... 0 new multiplicons found.
123 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
122 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
121 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
120 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
119 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
118 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
117 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
116 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
115 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
114 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
113 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
112 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
111 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
110 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
109 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
108 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
107 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
106 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
105 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
104 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
103 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
102 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
101 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
100 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
99 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
98 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
97 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
96 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
95 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
94 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
93 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
92 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
91 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
90 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
89 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
88 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
87 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
86 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
85 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
84 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
83 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
82 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
81 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
80 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
79 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
78 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
77 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
76 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
75 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
74 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
73 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
72 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
71 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
70 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
69 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
68 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
67 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
66 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
65 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
64 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
63 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
62 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
61 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
60 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
59 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
58 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
57 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
56 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
55 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
54 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
53 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
52 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
51 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
50 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
49 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
48 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
47 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
46 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
45 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
44 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
43 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
42 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
41 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
40 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
39 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
38 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
37 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
36 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
35 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
34 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
33 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
32 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
31 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
30 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
29 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
28 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
27 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
26 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
25 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
24 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
23 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
22 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
21 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
20 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
19 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
18 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
17 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
16 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
15 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
14 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
13 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
12 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
11 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
10 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
9 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
8 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
7 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
6 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
5 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
4 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
3 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
2 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
1 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
Flushing output files...Visualize AlignedProfiles
done.
Time for Higher Level Detection: 0.261017s.

All Done!  Bye...

2024-10-17 20:48:01: INFO       Drawing co-linearity dotplot
/home/yu123/.local/lib/python3.6/site-packages/wgd/viz.py:223: UserWarning: Attempting to set identical left == right == 0 results in singular transformations; automatically expanding.
  ax.set_xlim(0, max(x))
/home/yu123/.local/lib/python3.6/site-packages/wgd/viz.py:224: UserWarning: Attempting to set identical bottom == top == 0 results in singular transformations; automatically expanding.
  ax.set_ylim(0, max(x))
Traceback (most recent call last):
  File "/home/yu123/.local/bin/wgd", line 8, in <module>
    sys.exit(cli())
  File "/home/yu123/.local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/yu123/.local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/yu123/.local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yu123/.local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yu123/.local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/yu123/.local/lib/python3.6/site-packages/wgd_cli.py", line 857, in syn
    gene_attribute, min_length, ks_range, **iadhore_opts
  File "/home/yu123/.local/lib/python3.6/site-packages/wgd_cli.py", line 949, in syn_
    '{}.dotplot.svg'.format(os.path.basename(families)))
  File "/home/yu123/.local/lib/python3.6/site-packages/wgd/viz.py", line 244, in syntenic_dotplot
    [row['begin_x'], row['end_x']]]
  File "/home/yu123/.local/lib/python3.6/site-packages/wgd/viz.py", line 243, in <listcomp>
    x = [genomic_elements[curr_list_x] + x for x in
KeyError: 94.0

Ask for help, thank you!

**Comment by arzwa** [comment]
Please use the updated version of `wgd` (available [here](https://github.com/heche-psb/wgd)) and if you still have problems, open an issue there.
